publish_acceleration: true
print_diagnostics: true
two_d_mode: true
transform_time_offset: 0
transform_timeout: 0.0
sensor_timeout: 0.5
frequency: 20
odom0: /icart_mini/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               true, true, true,
               false, false, false]
imu0: /imu_data
imu0_config: [false, false, false,
               false, false, false,
               false, false, false,
               true, true, true,
               true, true, true]
